// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

///  Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDObO_jr_Gc4ZL1FwrU4oU6ewN6Y1JUARU',
    appId: '1:395540117439:web:4cff9fd46cf5d54567d30a',
    messagingSenderId: '395540117439',
    projectId: 'gigjob-mobile',
    authDomain: 'gigjob-mobile.firebaseapp.com',
    storageBucket: 'gigjob-mobile.appspot.com',
    measurementId: 'G-FTW8GW2R07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDggaiV6q_HzlX1RAxU-s4uj0gFg6zgojM',
    appId: '1:395540117439:android:4795f18430d28a6167d30a',
    messagingSenderId: '395540117439',
    projectId: 'gigjob-mobile',
    storageBucket: 'gigjob-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBznnXqf0k_NCiamta00H2VQG3l9M4W6No',
    appId: '1:395540117439:ios:492e2173a672318a67d30a',
    messagingSenderId: '395540117439',
    projectId: 'gigjob-mobile',
    storageBucket: 'gigjob-mobile.appspot.com',
    iosClientId:
        '395540117439-hriqo5e2ka4g8dotnh77a8uog4u4olh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gigjobMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBznnXqf0k_NCiamta00H2VQG3l9M4W6No',
    appId: '1:395540117439:ios:492e2173a672318a67d30a',
    messagingSenderId: '395540117439',
    projectId: 'gigjob-mobile',
    storageBucket: 'gigjob-mobile.appspot.com',
    iosClientId:
        '395540117439-hriqo5e2ka4g8dotnh77a8uog4u4olh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gigjobMobile',
  );
}
